// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Sample API
//
//	API description in Markdown.
//	Schemes:
//	  https
//	Host: api.example.com
//	BasePath: /v2
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
